### ISSUE TITLE
Interpretation of results of two-sample test

### ISSUE THREAD

**Issue by pmiszkiewicz** [Gabinou/2DKS#2]
Hello,
first thank you very much for this implementation, I have looked for something similar for a very long time and this will help me a lot in my master's thesis (of course I have given credit to you for the code). I have a few questions regarding how to understand the results of two tests I have done on populations:

1. A and B
2. A and C (C is a subset of B)

The results I got are, respectively:

1. (0.07785494519464609, 0.0)
2. (0.17752050146508203, 0.0)

For both prob = 0, so I can obviously reject the null hypothesis. But can I refer to this value as the p-value like when I do an univariate K-S test? Also, can I understand the difference in D value, that distribution of C is more different from A than B? Finally, does the D in your code refer to D_BKS or Z_n in the original Foseno-Franceschini paper, or to another value?

Thank you in advance for your help.

Best regards
Przemek

**Comment by Gabinou** [comment]
Dear Przemek,

The output of ks2d is (D, prob), with D the KS test statistic and prob the significance level as they are shown [3] Numerical Recipes in C. 

I have no grasp on what a p-value is, and I don't know what is the relationship between the output of ks2d2s and a p-value.

Best Regards,
Gabriel Taillon
